build: false
image:
  - MacOS
  - Visual Studio 2019

environment:

  global:
    PYTHONUNBUFFERED: "1"
    INSTALL_EDM_VERSION: "3.0.1"
    APPVEYOR_YML_DISABLE_PS_LINUX: true

  matrix:

    - RUNTIME: '3.6'

cache:
  - C:\Users\appveyor\.cache -> appveyor-clean-cache.txt
  - C:\Users\appveyor\AppData\Local\pip\Cache -> appveyor-clean-cache.txt
  - '${HOME}/cache -> appveyor-clean-cache.txt'

init:
  - ps: $Env:path = "C:/Enthought/edm;" + $Env:path
  - ps: md C:/Users/appveyor/.cache -Force
  # note that on osx the .cache folder is owned by root
  # and we cannot create files there.
  - sh: export PATH="${PATH}:/usr/local/bin"
  - sh: export XDG_CACHE_HOME="${HOME}/cache"
  - sh: export LC_ALL=en_US.UTF-8
  - sh: export LANG=en_US.UTF-8
  - sh: mkdir -p "${HOME}/cache/download"
  - sh: sysctl -n machdep.cpu.brand_string

install:
  - cmd: install-edm-windows.cmd
  - sh: ./install-edm-osx.sh
  - edm install -y wheel click coverage
  - sh: edm run -- python etstool.py install --runtime="${RUNTIME}"
  - cmd: edm run -- python etstool.py install --runtime=%runtime%
test_script:
  - sh: edm run -- python etstool.py test --runtime="${RUNTIME}"
  - cmd: edm run -- python etstool.py test --runtime=%runtime%
