#define HID_Edit_Rule_Based_Filter_Dialog_Box	2006
#define HID_Converge_Connection_Editor_dlg	2000
#define HID_Create_a_New_Log_dlg	2001
#define HID_Customize_Filters_dlg	2002
#define HID_Edit_Filter_For_Inputs_dlg	2003
#define HID_Edit_Filter_For_Outputs_dlg	2004
#define HID_Edit_Menu_Based_Filter_dlg	2005
#define HID_Select_and_Order_Columns_dlg	2009
#define HID_Model_wnd	2010
#define HID_Script_wnd	2011
#define HID_Function_Browser_Dlg	2012
#define HID_Workflow_Properties_Dlg	2013
#define HID_Quality_Agent_Dlg	2014
#define HID_Import_Item_Dlg	2007
#define HID_Workbench_Preferences	2015
#define HID_Logger_Preferences	2016
#define HID_Additions_Preferences	2017
#define HID_Script_Editing_Wnd	2008
