# This workflow targets stable released dependencies from EDM.
# Note that some packages may not actually be installed from EDM but from
# PyPI, see etstool.py implementations.

name: Test with EDM

on: [pull_request, workflow_dispatch]

env:
  INSTALL_EDM_VERSION: 3.7.0

jobs:

  # Test against EDM packages
  test-with-edm:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        runtime: ['3.8', '3.11']

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the target commit
        uses: actions/checkout@v4
      - name: Set up bootstrap Python (3.10)
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: '.github/workflows/bootstrap-requirements.txt'
      - name: Install necessary packages to the bootstrap environment
        run: python -m pip install -r .github/workflows/bootstrap-requirements.txt
      - name: Cache EDM packages
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: ${{ runner.os }}-${{ matrix.runtime }}-${{ hashFiles('etstool.py') }}
      - name: Setup EDM
        uses: enthought/setup-edm-action@v4
        with:
          edm-version: ${{ env.INSTALL_EDM_VERSION }}
      - name: Install test environment
        run: python etstool.py install --runtime=${{ matrix.runtime }}
      - name: Run style checks (only on Linux, 3.8)
        run: python etstool.py flake8 --runtime=${{ matrix.runtime }}
        if: startsWith(matrix.os, 'ubuntu') && matrix.runtime == '3.8'
      - name: Run tests
        run: python etstool.py test --runtime=${{ matrix.runtime }}
